### ISSUE TITLE
Error getting file in OnlyOffice connector with application authenticaiton in PostgreSQL

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#747]
When we get file, anyway we try to get user information with plugin identifier. In PostgreSQL it's uuid and we have type conversion error

```json
{
  "level": 30,
  "time": 1732688295035,
  "pid": 18,
  "hostname": "tdrive-backend-578d74d8bc-6sxwn",
  "name": "TdriveApp",
  "request_id": "req-1d8",
  "user_id": "tdrive_onlyoffice",
  "user_email": null,
  "msg": "500 GET /internal/services/documents/v1/companies/00000000-0000-4000-0000-000000000000/item/1aac2e34-1810-4535-b6fe-958ce322ea12",
  "length": 149,
  "name": "error",
  "severity": "ERROR",
  "code": "22P02",
  "where": "unnamed portal parameter $1 = '...'",
  "file": "uuid.c",
  "line": "133",
  "routine": "string_to_uuid",
  "stack": "error: invalid input syntax for type uuid: \"tdrive_onlyoffice\"\n    at /usr/src/app/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresConnector.find (/usr/src/app/dist/core/platform/services/database/services/orm/connectors/postgres/postgres.js:165:25)\n    at async Repository.find (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:46:16)\n    at async Repository.findOne (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:52:17)\n    at async UserServiceImpl.get (/usr/src/app/dist/services/user/services/users/service.js:168:16)\n    at async getVirtualFoldersNames (/usr/src/app/dist/services/documents/utils.js:36:18)\n    at async getPath (/usr/src/app/dist/services/documents/utils.js:220:19)\n    at async getPath (/usr/src/app/dist/services/documents/utils.js:237:21)\n    at async DocumentsService.get (/usr/src/app/dist/services/documents/services/index.js:202:19)\n    at async DocumentsController.get (/usr/src/app/dist/services/documents/web/controllers/documents.js:112:17)",
  "type": "Error"
}
```

```

at async DocumentsController.get (/usr/src/app/dist/services/documents/web/controllers/documents.js:112:17) { |  
-- | --
  |   | 2024-11-27 07:18:15.035 | at async DocumentsService.get (/usr/src/app/dist/services/documents/services/index.js:202:19) |  
  |   | 2024-11-27 07:18:15.035 | at async getPath (/usr/src/app/dist/services/documents/utils.js:237:21) |  
  |   | 2024-11-27 07:18:15.035 | at async getPath (/usr/src/app/dist/services/documents/utils.js:220:19) |  
  |   | 2024-11-27 07:18:15.035 | at async getVirtualFoldersNames (/usr/src/app/dist/services/documents/utils.js:36:18) |  
  |   | 2024-11-27 07:18:15.035 | at async UserServiceImpl.get (/usr/src/app/dist/services/user/services/users/service.js:168:16) |  
  |   | 2024-11-27 07:18:15.034 | at async Repository.findOne (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:52:17) |  
  |   | 2024-11-27 07:18:15.034 | at async Repository.find (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:46:16) |  
  |   | 2024-11-27 07:18:15.034 | at async PostgresConnector.find (/usr/src/app/dist/core/platform/services/database/services/orm/connectors/postgres/postgres.js:165:25) |  
  |   | 2024-11-27 07:18:15.034 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) |  
  |   | 2024-11-27 07:18:15.034 | at /usr/src/app/node_modules/pg/lib/client.js:526:17 |  
  |   | 2024-11-27 07:18:15.034 | Got 200 error on request req-1d8 :  error: invalid input syntax for type uuid: "tdrive_onlyoffice"


```

**Comment by ericlinagora** [comment]
fixed in 1.0.5-rc11
